config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources :articles do
  	resources :comments
  	collection do 
  		get 'mine'
  	end 
  end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_one_attached :image
	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :title, presence: true
  validates :body, presence: true

  def self.ransackable_attributes(auth_object=null)
  	["id", "title", "body"]
  end

  ransacker :id_to_s do 
  Arel.sql("regexp_replace(to_char(\"#{table_name}\".\"id\", '9999999'), ' ', '', 'g')")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_global_search_variable
	def set_global_search_variable
  	@q = Article.ransack(params[:q])
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show,:search]
  before_action :correct_user, only:[:edit,:update,:destroy]
  before_action :set_global_search_variable
  def index
    # if params[:q].present?
    @q=Article.ransack(params[:q])
    @articles=@q.result.order("created_at ASC").page(params[:page])
  	#@articles=Article.all.order("created_at ASC").page(params[:page])
    # else
    #   redirect_to(root_path,alert:"Empty Field")
    # end
  end

  def mine
    @article=Article.where(user_id: current_user.id)
  end

   def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  def correct_user
    @article=current_user.articles.find_by(id: params[:id])
    redirect_to articles_path ,notice:"Not Authorized for this action" if @article.nil?
  end

  private
    def article_params
      params.require(:article).permit(:title, :body,:user_id,:image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="form-group">
    <% form.label :title %><br>
    <%= form.text_field :title, class:"form-control",placeholder:"Title" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <% form.label :body %><br>
    <%= form.text_area :body, class:"form-control",placeholder:"Body" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <% if article.image.attached? %>
    <%= form.label:Image %>
  </br>
    <%= image_tag(article.image, :size => "260x180") %>
    <% end %>
    <%= form.file_field:image ,class:"form-control" %>
  </div>

  <div class="form-group">
    <% form.label :user %>
    <%= form.text_field :user_id, class:"form-control",value:current_user.id , type: :hidden %><br>
  </div>

  <div >
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Articles', root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> -->
        <%if user_signed_in? %>
        <li class="nav-item">
          <%=link_to 'My Articles', mine_articles_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to 'Add Article',new_article_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to 'Sign Out',destroy_user_session_path,method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to 'Edit profile',edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%=link_to 'Sign In',new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to 'Sign Up',new_user_registration_path,class:"nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="form-inline my-2 my-lg-0 form_control">
      <%= search_form_for @q do |f|%>
      <%= f.search_field :title_or_body_cont,placeholder:"Search"%>
      <% end %>

    </div>
 <!--    
  </div>
   <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  
  </div>
  -->
</nav>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

 
 <%= search_form_for @q do |f| %>
  <div class="field">
    <%= f.label:id_eq,"Search " %>
    <%= f.search_field:id_eq %>
</div>
</br>
<% end %>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Body</th>
      </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
    <% #if article.user == current_user %>
      <tr>
        <td><%= link_to article.title , article %></td> 
        <td><%= article.body %></td>
      </tr>
      <% #end %>
    <% end %>
  </tbody>
</table>
<%= paginate @articles%>
</br>

app/views/articles/mine.html.erb
<p id="notice"><%= notice %></p>

<h1>My Articles</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Body</th>
      </tr>
  </thead>

  <tbody>
    <% @article.each do |article| %>
    <% #if article.user == current_user %>
      <tr>
        <td><%= link_to article.title , article %></td> 
        <td><%= article.body %></td>
      </tr>
      <% #end %>
    <% end %>
  </tbody>
</table>

</br>

app/views/articles/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Article</h1>

<%= render 'form', article: @article %>
</br>
<%= link_to 'Cancel', root_path,class:"btn btn-outline-danger"%>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1 class="display-4">
    <div>
    <% if @article.image.attached? %>
    <%= image_tag(@article.image, :size => "260x180") %>
    <% end %>
  </div>
  	<h1><%= @article.title %></h1>
  </h1>
  <p><%= @article.body %></p>

  <hr class="my-4">
  <p class="lead">
    <a href="#" role="button">
    
  <%= link_to "Edit", edit_article_path(@article) ,class:"btn btn-outline-secondary"%>
  <%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } ,class:"btn btn-outline-danger"%>
  <%= link_to "Back", root_path(@article) ,class:"btn btn-outline-secondary"%>
    </a>
  </p>
</div>

<h2>Comments</h2>
<%= render @article.comments %>
</br>
<% if user_signed_in? %>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<% end %>

app/views/comments/_comment.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="width: 18rem;">
  
  <div class="card-body">
    <h4 >
      <%= comment.commenter %>
    </h4>
    <p class="lead">
      <%= comment.body %>
    </p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" },class:"btn btn-outline-danger"%>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="form-group">
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <% form.label :commenter %><br>
    <%= form.text_field :commenter,class:"form-control",placeholder:"Your Name" %>
  </p>
  <p>
    <% form.label :body %><br>
    <%= form.text_area :body,class:"form-control",placeholder:"Comment" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Blog1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  </br>
  <body >
    <%= render 'articles/header' %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>